name: screen
description: A Flutter plugin to manage the device's screen on Android and iOS.
version: 0.0.5
author: Clovis Nicolas <clovisnicolas0@gmail.com>
homepage: https://github.com/clovisnicolas/flutter_screen

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.screen.screen
        pluginClass: ScreenPlugin
      ios:
        pluginClass: ScreenPlugin